// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_pT1X969Izyn1YguS0qrOIoTe27so-fo',
    appId: '1:273987414414:web:48bc7d03723b18ba2f5cdf',
    messagingSenderId: '273987414414',
    projectId: 'mobieappcocktail',
    authDomain: 'mobieappcocktail.firebaseapp.com',
    storageBucket: 'mobieappcocktail.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSQLdUvHUfGQfx4MEN7lFDO1zAN1U7Gk',
    appId: '1:273987414414:android:e802612662c60bba2f5cdf',
    messagingSenderId: '273987414414',
    projectId: 'mobieappcocktail',
    storageBucket: 'mobieappcocktail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBmvi9cDTjhk0ag7brjohHcc9Pc4MeOM',
    appId: '1:273987414414:ios:61e58c280e175d0e2f5cdf',
    messagingSenderId: '273987414414',
    projectId: 'mobieappcocktail',
    storageBucket: 'mobieappcocktail.appspot.com',
    iosClientId: '273987414414-1spu97g868p8970gvboj3bbsap3mn5l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.baiTapLon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIBmvi9cDTjhk0ag7brjohHcc9Pc4MeOM',
    appId: '1:273987414414:ios:61e58c280e175d0e2f5cdf',
    messagingSenderId: '273987414414',
    projectId: 'mobieappcocktail',
    storageBucket: 'mobieappcocktail.appspot.com',
    iosClientId: '273987414414-1spu97g868p8970gvboj3bbsap3mn5l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.baiTapLon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_pT1X969Izyn1YguS0qrOIoTe27so-fo',
    appId: '1:273987414414:web:a93612f5bfea1bcd2f5cdf',
    messagingSenderId: '273987414414',
    projectId: 'mobieappcocktail',
    authDomain: 'mobieappcocktail.firebaseapp.com',
    storageBucket: 'mobieappcocktail.appspot.com',
  );

}